"""Module of wrapper classes."""
from gym_dogfight import error
from gym_dogfight.wrappers.atari_preprocessing import AtariPreprocessing
from gym_dogfight.wrappers.autoreset import AutoResetWrapper
from gym_dogfight.wrappers.clip_action import ClipAction
from gym_dogfight.wrappers.filter_observation import FilterObservation
from gym_dogfight.wrappers.flatten_observation import FlattenObservation
from gym_dogfight.wrappers.frame_stack import FrameStack, LazyFrames
from gym_dogfight.wrappers.gray_scale_observation import GrayScaleObservation
from gym_dogfight.wrappers.human_rendering import HumanRendering
from gym_dogfight.wrappers.normalize import NormalizeObservation, NormalizeReward
from gym_dogfight.wrappers.order_enforcing import OrderEnforcing
from gym_dogfight.wrappers.record_episode_statistics import RecordEpisodeStatistics
from gym_dogfight.wrappers.record_video import RecordVideo, capped_cubic_video_schedule
from gym_dogfight.wrappers.render_collection import RenderCollection
from gym_dogfight.wrappers.rescale_action import RescaleAction
from gym_dogfight.wrappers.resize_observation import ResizeObservation
from gym_dogfight.wrappers.step_api_compatibility import StepAPICompatibility
from gym_dogfight.wrappers.time_aware_observation import TimeAwareObservation
from gym_dogfight.wrappers.time_limit import TimeLimit
from gym_dogfight.wrappers.transform_observation import TransformObservation
from gym_dogfight.wrappers.transform_reward import TransformReward
from gym_dogfight.wrappers.vector_list_info import VectorListInfo
